// Generated by CoffeeScript 1.3.3
(function() {
  var GalaxyModel;

  GalaxyModel = [];

  GalaxyModel.VERSION = '0.0.1';

  GalaxyModel.Model = require('./model');

  GalaxyModel.models = require('./models');

  GalaxyModel.Residual = require('./residual');

  if (typeof module !== "undefined" && module !== null) {
    module.exports = GalaxyModel;
  }

}).call(this);
