// Generated by CoffeeScript 1.3.3
(function() {
  var Model, Residual;

  Residual = require('./residual');

  Model = (function() {

    function Model(fitsImage, modelFunc, params) {
      this.fitsImage = fitsImage;
      this.modelFunc = modelFunc;
      this.params = params;
      this.width = this.fitsImage.width;
      this.height = this.fitsImage.height;
      this.fitsData = this.fitsImage.data;
      this.length = this.width * this.height;
      this.modelBuffer = new ArrayBuffer(this.length * 4);
      this.data = new Float32Array(this.modelBuffer);
      this.residual = new Residual(this.width, this.height);
      this.residualData = this.residual.data;
    }

    Model.prototype.generate = function() {
      this.modelFunc(this.data, this.width, this.height, this.params);
      return void 0;
    };

    Model.prototype.calculateResidual = function() {
      var index, _i, _ref;
      for (index = _i = 0, _ref = this.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; index = 0 <= _ref ? ++_i : --_i) {
        this.residualData[index] = this.fitsData[index] - this.data[index];
      }
      return void 0;
    };

    return Model;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Model;
  }

}).call(this);
